### ISSUE TITLE
Email cím és jelszó beállítása (jelszó még egyszer)

### ISSUE THREAD

**Issue by InfoDigitalInn** [rgaspar/ts-development#21]
Nem engedte Misi Mókust elmenteni. Azt írja, hogy betűk és karakterek kell, hogy legyenek, pedig ide magyar emberek lesznek, ékezetes nevekkel.

**Comment by rgaspar** [comment]
Username nem egyenlő a sima névvel. Ide ékezetek nélküli felhasználó nevet kell megadni.
