### ISSUE TITLE
Email megerősítés

### ISSUE THREAD

**Issue by InfoDigitalInn** [rgaspar/ts-development#52]
Nem érkezik email a regisztráció megerősítéséhez!

**Comment by rgaspar** [comment]
Szia! 

Pedig kiment, csatoltam a kepet. 

![image](https://user-images.githubusercontent.com/4813961/83501920-22efb680-a4c1-11ea-9caf-7d1650a4076f.png)

**Comment by InfoDigitalInn** [comment]
Igen, már megtaláltam, Levélszemétbe rakta! Köszi!

**Comment by InfoDigitalInn** [comment]
Ki kellene rakni egy kis note-ot, hogy ellenőrizzék le a Levélszemétbe is az emailt!
